### ISSUE TITLE
A note on SMOG score

### ISSUE THREAD

**Issue by i-trofimtschuk** [wimmuskee/readability-score#1]
To correctly determine the SMOG score, you need at least 30 sentences, where there are 10 consecutive of them taken from the beginning, the middle and the end of the text respectively.

Source: http://webpages.charter.net/ghal/SMOG_Readability_Formula_G._Harry_McLaughlin_(1969).pdf

**Comment by wimmuskee** [comment]
and finally fixed properly

**Comment by i-trofimtschuk** [comment]
:+1:
